### PR TITLE
Cleanup and leave command

### PR DESCRIPTION
**Pull request by arbauman**
Replaced a few vars and lets with const, added semicolons everywhere.

Added a leave command as per #9, seems to work fine.  It leaves the guilds file alone, so it'll rejoin on restart, but it sounded like that's what you were intending.  If not, let me know.

### CODE REVIEW

**Comment by Geo1088** [comment]
> added semicolons everywhere

Ehh... I'm gonna say no to this. My project, my style, and all that.

> Added a leave command as per #9, seems to work fine. It leaves the guilds file alone, so it'll rejoin on restart, but it sounded like that's what you were intending.

Yeah, it would need to remove the guild's `vc` entry. Not saving the change would be confusing if the bot died, which happens rather frequently at the moment for various other reasons.

I haven't checked any code here, and probably won't get the chance to until later tonight. (10h or so)

**Comment by arbauman** [comment]
You're right, I dunno what I was thinking.

I updated the command, which now replaces the guild's 'vc' value with null.  I tested it on my server:

- When in a voice channel and told to leave, it leaves.
- If you restart the bot after it's told to leave, it will be in the server but will not rejoin the voice channel (or start tripping on errors)
- If told to join a channel, it will replace null with the voice channel ID as normal, functioning normally.

**Comment by Geo1088** [comment]
Sweet, thanks a ton for testing this. Not sure when these changes will go live on the main bot, but hopefully it'll be soon.

**Comment by Geo1088** [comment]
...I actually just realized we can probably use `delete` rather than setting the vc to null, I'll go over it and see if it's worth making another function for. Unless you want to PR that too, I'll probably add it in a later commit tonight.

**Comment by arbauman** [comment]
I just did that, and as far as I can tell it's working correctly.  However, even though it seems to be working just fine, it's throwing 

(node:17285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id 1): Error: 403 FORBIDDEN

Any ideas where that's coming from?  It happens both when the bot joins a channel and leaves.

**Comment by Geo1088** [comment]
Uh... 403s being thrown means Eris is doing something wrong, but if it's working anyway I'm not sure what would be throwing it. Could you push the changes you've got so far to your fork so I can check it out more closely?

**Comment by arbauman** [comment]
Yeah, it's up now.

**Pull request merged**
